`define DUT             u_ktp
`define mst_awready     `DUT.awready_s
`define mst_arready     `DUT.arready_s
`define mst_rvalid      `DUT.rvalid_s
`define mst_rlast       `DUT.rlast_s
`define mst_rdata       `DUT.rdata_s
`define mst_rresp       `DUT.rresp_s
`define mst_rid         `DUT.rid_s
`define mst_ruser       `DUT.ruser_s
`define mst_bvalid      `DUT.bvalid_s
`define mst_bresp       `DUT.bresp_s
`define mst_bid         `DUT.bid_s
`define mst_buser       `DUT.buser_s
`define mst_awvalid     `DUT.awvalid_s
`define mst_awaddr      `DUT.awaddr_s
`define mst_awlen       `DUT.awlen_s
`define mst_awsize      `DUT.awsize_s
`define mst_awburst     `DUT.awburst_s
`define mst_awlock      `DUT.awlock_s
`define mst_awcache     `DUT.awcache_s
`define mst_awprot `DUT.awprot_s
`define mst_awid `DUT.awid_s
`define mst_awregion `DUT.awregion_s
`define mst_awuser `DUT.awuser_s
`define mst_awqos `DUT.awqos_s
`define mst_arvalid `DUT.arvalid_s
`define mst_araddr `DUT.araddr_s
`define mst_arlen `DUT.arlen_s
`define mst_arsize `DUT.arsize_s
`define mst_arburst `DUT.arburst_s
`define mst_arlock `DUT.arlock_s
`define mst_arcache `DUT.arcache_s
`define mst_arprot `DUT.arprot_s
`define mst_arid `DUT.arid_s
`define mst_arregion `DUT.arregion_s
`define mst_aruser `DUT.aruser_s
`define mst_arqos `DUT.arqos_s
`define mst_rready `DUT.rready_s
`define mst_wvalid `DUT.wvalid_s
`define mst_wlast `DUT.wlast_s
`define mst_wdata `DUT.wdata_s
`define mst_wstrb `DUT.wstrb_s
`define mst_wuser `DUT.wuser_s
`// define mst_wid
`define mst_wready `DUT.wready_s
`define mst_bready `DUT.bready_s

`define mst_awdomain `DUT.awdomain_s
`define mst_ardomain `DUT.ardomain_s
`define mst_awsnop `DUT.awsnop_s
`define mst_arsnoop `DUT.arsnoop_s
`define mst_awbarrier `DUT.awbar_s
`define mst_arbarrier `DUT.arbar_s

`define slv_awcache `DUT.awcache_m
`define slv_awprot `DUT.awprot_m
`define slv_awuser `DUT.awuser_m
`define slv_awqos `DUT.awqos_m
`define slv_awid `DUT.awid_m
`define slv_arvalid `DUT.arvalid_m
`define slv_araddr `DUT.araddr_m
`define slv_arlen `DUT.arlen_m
`define slv_arsize `DUT.arsize_m
`define slv_arburst `DUT.arburst_m
`define slv_arlock `DUT.arlock_m
`define slv_arcache `DUT.arcache_m
`define slv_arprot `DUT.arprot_m
`define slv_aruser `DUT.aruser_m
`define slv_arqos `DUT.arqos_m
`define slv_arid `DUT.arid_m
`define slv_rready `DUT.rready_m
`define slv_wvalid `DUT.wvalid_m
`define slv_wlast `DUT.wlast_m
`define slv_wdata `DUT.wdata_m
`define slv_wstrb `DUT.wstrb_m
// define slv_wid `DUT.wid_m
`define slv_wuser `DUT.wuser_m
`define slv_bready `DUT.bready_m
`define slv_awready `DUT.awready_m
`define slv_arready `DUT.arready_m
`define slv_rvalid `DUT.rvalid_m
`define slv_rlast `DUT.rlast_m
`define slv_rdata `DUT.rdata_m
`define slv_rresp `DUT.rresp_m
`define slv_rid `DUT.rid_m
`define slv_wready `DUT.wready_m
`define slv_bvalid `DUT.bvalid_m
`define slv_bresp `DUT.bresp_m
`define slv_bid `DUT.bid_m
`define slv_ruser `DUT.ruser_m
`define slv_awlock `DUT.awlock_m
`define slv_awvalid `DUT.awvalid_m
`define slv_awaddr `DUT.awaddr_m
`define slv_awlen `DUT.awlen_m
`define slv_awsize `DUT.awsize_m
`define slv_awburst `DUT.awburst_m
`define slv_awuser `DUT.awuser_m
`define slv_ardomain `DUT.ardomain_m
`define slv_awdomain `DUT.awdomain_m
`define slv_arbarrier `DUT.arbar_m
`define slv_awregion `DUT.awregion_m
`define slv_awsnoop `DUT.awsnoop_m
`define slv_arsnoop `DUT.arsnoop_m
`define slv_arregion `DUT.arregion_m
`define slv_awbarrier `DUT.awbar_m

`define cfg_psel `DUT.psel
`define cfg_penable `DUT.penable
`define cfg_pwrite `DUT.pwrite
`define cfg_paddr `DUT.paddr
`define cfg_pwdata `DUT.pwdata
`define cfg_pstrb `DUT.pstrb
`define cfg_pprot `DUT.pprot
`define cfg_prdata `DUT.prdata
`define cfg_pslverr `DUT.pslverr
`define cfg_pready `DUT.pready


